# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from pay_pal_invoicing_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from pay_pal_invoicing_python_sdk.api_response import AsyncGeneratorResponse
from pay_pal_invoicing_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_invoicing_python_sdk import schemas  # noqa: F401

from pay_pal_invoicing_python_sdk.model.model202_response import Model202Response as Model202ResponseSchema
from pay_pal_invoicing_python_sdk.model.error422 import Error422 as Error422Schema
from pay_pal_invoicing_python_sdk.model.error404 import Error404 as Error404Schema
from pay_pal_invoicing_python_sdk.model.error403 import Error403 as Error403Schema
from pay_pal_invoicing_python_sdk.model.error_default import ErrorDefault as ErrorDefaultSchema
from pay_pal_invoicing_python_sdk.model.error400 import Error400 as Error400Schema
from pay_pal_invoicing_python_sdk.model.notification import Notification as NotificationSchema
from pay_pal_invoicing_python_sdk.model.link_description import LinkDescription as LinkDescriptionSchema

from pay_pal_invoicing_python_sdk.type.error404 import Error404
from pay_pal_invoicing_python_sdk.type.error400 import Error400
from pay_pal_invoicing_python_sdk.type.error_default import ErrorDefault
from pay_pal_invoicing_python_sdk.type.notification import Notification
from pay_pal_invoicing_python_sdk.type.model202_response import Model202Response
from pay_pal_invoicing_python_sdk.type.error422 import Error422
from pay_pal_invoicing_python_sdk.type.link_description import LinkDescription
from pay_pal_invoicing_python_sdk.type.error403 import Error403

from ...api_client import Dictionary
from pay_pal_invoicing_python_sdk.pydantic.error404 import Error404 as Error404Pydantic
from pay_pal_invoicing_python_sdk.pydantic.error403 import Error403 as Error403Pydantic
from pay_pal_invoicing_python_sdk.pydantic.error_default import ErrorDefault as ErrorDefaultPydantic
from pay_pal_invoicing_python_sdk.pydantic.notification import Notification as NotificationPydantic
from pay_pal_invoicing_python_sdk.pydantic.model202_response import Model202Response as Model202ResponsePydantic
from pay_pal_invoicing_python_sdk.pydantic.link_description import LinkDescription as LinkDescriptionPydantic
from pay_pal_invoicing_python_sdk.pydantic.error400 import Error400 as Error400Pydantic
from pay_pal_invoicing_python_sdk.pydantic.error422 import Error422 as Error422Pydantic

from . import path

# Path params
InvoiceIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'invoice_id': typing.Union[InvoiceIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_invoice_id = api_client.PathParameter(
    name="invoice_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=InvoiceIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = NotificationSchema


request_body_notification = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_auth = [
    'Oauth2',
]
SchemaFor200ResponseBodyApplicationJson = LinkDescriptionSchema
SchemaFor200ResponseBodyMultipartMixed = LinkDescriptionSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: LinkDescription


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: LinkDescription


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor200ResponseBodyMultipartMixed),
    },
)
SchemaFor202ResponseBodyApplicationJson = Model202ResponseSchema
SchemaFor202ResponseBodyMultipartMixed = Model202ResponseSchema


@dataclass
class ApiResponseFor202(api_client.ApiResponse):
    body: Model202Response


@dataclass
class ApiResponseFor202Async(api_client.AsyncApiResponse):
    body: Model202Response


_response_for_202 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor202,
    response_cls_async=ApiResponseFor202Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor202ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor202ResponseBodyMultipartMixed),
    },
)
SchemaFor400ResponseBodyApplicationJson = Error400Schema
SchemaFor400ResponseBodyMultipartMixed = Error400Schema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: Error400


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: Error400


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor400ResponseBodyMultipartMixed),
    },
)
SchemaFor403ResponseBodyApplicationJson = Error403Schema
SchemaFor403ResponseBodyMultipartMixed = Error403Schema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: Error403


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: Error403


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor403ResponseBodyMultipartMixed),
    },
)
SchemaFor404ResponseBodyApplicationJson = Error404Schema
SchemaFor404ResponseBodyMultipartMixed = Error404Schema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: Error404


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: Error404


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor404ResponseBodyMultipartMixed),
    },
)
SchemaFor422ResponseBodyApplicationJson = Error422Schema
SchemaFor422ResponseBodyMultipartMixed = Error422Schema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: Error422


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: Error422


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor422ResponseBodyMultipartMixed),
    },
)
SchemaFor0ResponseBodyApplicationJson = ErrorDefaultSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: ErrorDefault


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: ErrorDefault


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '202': _response_for_202,
    '400': _response_for_400,
    '403': _response_for_403,
    '404': _response_for_404,
    '422': _response_for_422,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
    'multipart/mixed',
)


class BaseApi(api_client.Api):

    def _send_invoice_mapped_args(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if subject is not None:
            _body["subject"] = subject
        if note is not None:
            _body["note"] = note
        if send_to_invoicer is not None:
            _body["send_to_invoicer"] = send_to_invoicer
        if send_to_recipient is not None:
            _body["send_to_recipient"] = send_to_recipient
        if additional_recipients is not None:
            _body["additional_recipients"] = additional_recipients
        args.body = _body
        if invoice_id is not None:
            _path_params["invoice_id"] = invoice_id
        args.path = _path_params
        return args

    async def _asend_invoice_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseFor202Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Send invoice
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_invoice_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/invoicing/invoices/{invoice_id}/send',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_notification.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _send_invoice_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseFor202,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Send invoice
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_invoice_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/invoicing/invoices/{invoice_id}/send',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_notification.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class SendInvoiceRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def asend_invoice(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseFor202Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._send_invoice_mapped_args(
            invoice_id=invoice_id,
            subject=subject,
            note=note,
            send_to_invoicer=send_to_invoicer,
            send_to_recipient=send_to_recipient,
            additional_recipients=additional_recipients,
        )
        return await self._asend_invoice_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def send_invoice(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseFor202,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._send_invoice_mapped_args(
            invoice_id=invoice_id,
            subject=subject,
            note=note,
            send_to_invoicer=send_to_invoicer,
            send_to_recipient=send_to_recipient,
            additional_recipients=additional_recipients,
        )
        return self._send_invoice_oapg(
            body=args.body,
            path_params=args.path,
        )

class SendInvoice(BaseApi):

    async def asend_invoice(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        validate: bool = False,
        **kwargs,
    ) -> LinkDescriptionPydantic:
        raw_response = await self.raw.asend_invoice(
            invoice_id=invoice_id,
            subject=subject,
            note=note,
            send_to_invoicer=send_to_invoicer,
            send_to_recipient=send_to_recipient,
            additional_recipients=additional_recipients,
            **kwargs,
        )
        if validate:
            return LinkDescriptionPydantic(**raw_response.body)
        return api_client.construct_model_instance(LinkDescriptionPydantic, raw_response.body)
    
    
    def send_invoice(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        validate: bool = False,
    ) -> LinkDescriptionPydantic:
        raw_response = self.raw.send_invoice(
            invoice_id=invoice_id,
            subject=subject,
            note=note,
            send_to_invoicer=send_to_invoicer,
            send_to_recipient=send_to_recipient,
            additional_recipients=additional_recipients,
        )
        if validate:
            return LinkDescriptionPydantic(**raw_response.body)
        return api_client.construct_model_instance(LinkDescriptionPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseFor202Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._send_invoice_mapped_args(
            invoice_id=invoice_id,
            subject=subject,
            note=note,
            send_to_invoicer=send_to_invoicer,
            send_to_recipient=send_to_recipient,
            additional_recipients=additional_recipients,
        )
        return await self._asend_invoice_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        invoice_id: str,
        subject: typing.Optional[str] = None,
        note: typing.Optional[str] = None,
        send_to_invoicer: typing.Optional[bool] = None,
        send_to_recipient: typing.Optional[bool] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseFor202,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._send_invoice_mapped_args(
            invoice_id=invoice_id,
            subject=subject,
            note=note,
            send_to_invoicer=send_to_invoicer,
            send_to_recipient=send_to_recipient,
            additional_recipients=additional_recipients,
        )
        return self._send_invoice_oapg(
            body=args.body,
            path_params=args.path,
        )

