# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_invoicing_python_sdk import schemas  # noqa: F401


class Phone(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The phone number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en).
    """


    class MetaOapg:
        required = {
            "country_code",
            "national_number",
        }
        
        class properties:
            
            
            class country_code(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 3
                    min_length = 1
                    regex=[{
                        'pattern': r'^[0-9]{1,3}?$',
                    }]
            
            
            class national_number(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 14
                    min_length = 1
                    regex=[{
                        'pattern': r'^[0-9]{1,14}?$',
                    }]
            
            
            class extension_number(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 15
                    min_length = 1
                    regex=[{
                        'pattern': r'^[0-9]{1,15}?$',
                    }]
            __annotations__ = {
                "country_code": country_code,
                "national_number": national_number,
                "extension_number": extension_number,
            }
    
    country_code: MetaOapg.properties.country_code
    national_number: MetaOapg.properties.national_number
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["country_code"]) -> MetaOapg.properties.country_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["national_number"]) -> MetaOapg.properties.national_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["extension_number"]) -> MetaOapg.properties.extension_number: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["country_code", "national_number", "extension_number", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["country_code"]) -> MetaOapg.properties.country_code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["national_number"]) -> MetaOapg.properties.national_number: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["extension_number"]) -> typing.Union[MetaOapg.properties.extension_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["country_code", "national_number", "extension_number", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        country_code: typing.Union[MetaOapg.properties.country_code, str, ],
        national_number: typing.Union[MetaOapg.properties.national_number, str, ],
        extension_number: typing.Union[MetaOapg.properties.extension_number, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Phone':
        return super().__new__(
            cls,
            *args,
            country_code=country_code,
            national_number=national_number,
            extension_number=extension_number,
            _configuration=_configuration,
            **kwargs,
        )
