# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_invoicing_python_sdk.type.amount_summary_detail import AmountSummaryDetail
from pay_pal_invoicing_python_sdk.type.email_address import EmailAddress
from pay_pal_invoicing_python_sdk.type.invoicer_info import InvoicerInfo
from pay_pal_invoicing_python_sdk.type.item import Item
from pay_pal_invoicing_python_sdk.type.money import Money
from pay_pal_invoicing_python_sdk.type.recipient_info import RecipientInfo
from pay_pal_invoicing_python_sdk.type.template_configuration import TemplateConfiguration
from pay_pal_invoicing_python_sdk.type.template_detail import TemplateDetail

class RequiredTemplateInfo(TypedDict):
    pass

class OptionalTemplateInfo(TypedDict, total=False):
    detail: TemplateDetail

    invoicer: InvoicerInfo

    # The billing and shipping information. Includes name, email, address, phone, and language.
    primary_recipients: typing.List[RecipientInfo]

    # An array of one or more CC: emails to which notifications are sent. If you omit this parameter, a notification is sent to all CC: email addresses that are part of the invoice.<blockquote><strong>Note:</strong> Valid values are email addresses in the `additional_recipients` value associated with the invoice.</blockquote>
    additional_recipients: typing.List[EmailAddress]

    # An array of invoice line-item information.
    items: typing.List[Item]

    configuration: TemplateConfiguration

    amount: AmountSummaryDetail

    due_amount: Money

class TemplateInfo(RequiredTemplateInfo, OptionalTemplateInfo):
    pass
