# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_invoicing_python_sdk.type.address_portable import AddressPortable
from pay_pal_invoicing_python_sdk.type.email_address import EmailAddress
from pay_pal_invoicing_python_sdk.type.link_description import LinkDescription
from pay_pal_invoicing_python_sdk.type.phone_detail import PhoneDetail
from pay_pal_invoicing_python_sdk.type.template import Template

class RequiredTemplates(TypedDict):
    pass

class OptionalTemplates(TypedDict, total=False):
    # An array of addresses in the user's PayPal profile.
    addresses: typing.List[AddressPortable]

    emails: EmailAddress

    # An array of phone numbers in the user's PayPal profile.
    phones: typing.List[PhoneDetail]

    # An array of details for each template. If `fields` is `none`, returns only the template name, ID, and default status.
    templates: typing.List[Template]

    # An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
    links: typing.List[LinkDescription]

class Templates(RequiredTemplates, OptionalTemplates):
    pass
