# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from pay_pal_invoicing_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from pay_pal_invoicing_python_sdk.api_response import AsyncGeneratorResponse
from pay_pal_invoicing_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_invoicing_python_sdk import schemas  # noqa: F401

from pay_pal_invoicing_python_sdk.model.configuration import Configuration as ConfigurationSchema
from pay_pal_invoicing_python_sdk.model.invoices_create_draft_invoice_response import InvoicesCreateDraftInvoiceResponse as InvoicesCreateDraftInvoiceResponseSchema
from pay_pal_invoicing_python_sdk.model.error_default import ErrorDefault as ErrorDefaultSchema
from pay_pal_invoicing_python_sdk.model.invoicer_info import InvoicerInfo as InvoicerInfoSchema
from pay_pal_invoicing_python_sdk.model.invoice import Invoice as InvoiceSchema
from pay_pal_invoicing_python_sdk.model.invoice_detail import InvoiceDetail as InvoiceDetailSchema
from pay_pal_invoicing_python_sdk.model.payments import Payments as PaymentsSchema
from pay_pal_invoicing_python_sdk.model.invoices_create_draft_invoice400_response import InvoicesCreateDraftInvoice400Response as InvoicesCreateDraftInvoice400ResponseSchema
from pay_pal_invoicing_python_sdk.model.error403 import Error403 as Error403Schema
from pay_pal_invoicing_python_sdk.model.refunds import Refunds as RefundsSchema
from pay_pal_invoicing_python_sdk.model.invoices_create_draft_invoice422_response import InvoicesCreateDraftInvoice422Response as InvoicesCreateDraftInvoice422ResponseSchema
from pay_pal_invoicing_python_sdk.model.invoice_status import InvoiceStatus as InvoiceStatusSchema
from pay_pal_invoicing_python_sdk.model.recipient_info import RecipientInfo as RecipientInfoSchema
from pay_pal_invoicing_python_sdk.model.link_description import LinkDescription as LinkDescriptionSchema
from pay_pal_invoicing_python_sdk.model.item import Item as ItemSchema
from pay_pal_invoicing_python_sdk.model.money import Money as MoneySchema
from pay_pal_invoicing_python_sdk.model.amount_summary_detail import AmountSummaryDetail as AmountSummaryDetailSchema

from pay_pal_invoicing_python_sdk.type.amount_summary_detail import AmountSummaryDetail
from pay_pal_invoicing_python_sdk.type.payments import Payments
from pay_pal_invoicing_python_sdk.type.money import Money
from pay_pal_invoicing_python_sdk.type.item import Item
from pay_pal_invoicing_python_sdk.type.invoice_detail import InvoiceDetail
from pay_pal_invoicing_python_sdk.type.invoice_status import InvoiceStatus
from pay_pal_invoicing_python_sdk.type.refunds import Refunds
from pay_pal_invoicing_python_sdk.type.error403 import Error403
from pay_pal_invoicing_python_sdk.type.configuration import Configuration
from pay_pal_invoicing_python_sdk.type.invoices_create_draft_invoice400_response import InvoicesCreateDraftInvoice400Response
from pay_pal_invoicing_python_sdk.type.invoices_create_draft_invoice_response import InvoicesCreateDraftInvoiceResponse
from pay_pal_invoicing_python_sdk.type.error_default import ErrorDefault
from pay_pal_invoicing_python_sdk.type.recipient_info import RecipientInfo
from pay_pal_invoicing_python_sdk.type.link_description import LinkDescription
from pay_pal_invoicing_python_sdk.type.invoicer_info import InvoicerInfo
from pay_pal_invoicing_python_sdk.type.invoices_create_draft_invoice422_response import InvoicesCreateDraftInvoice422Response
from pay_pal_invoicing_python_sdk.type.invoice import Invoice

from ...api_client import Dictionary
from pay_pal_invoicing_python_sdk.pydantic.error403 import Error403 as Error403Pydantic
from pay_pal_invoicing_python_sdk.pydantic.link_description import LinkDescription as LinkDescriptionPydantic
from pay_pal_invoicing_python_sdk.pydantic.invoices_create_draft_invoice_response import InvoicesCreateDraftInvoiceResponse as InvoicesCreateDraftInvoiceResponsePydantic
from pay_pal_invoicing_python_sdk.pydantic.invoices_create_draft_invoice400_response import InvoicesCreateDraftInvoice400Response as InvoicesCreateDraftInvoice400ResponsePydantic
from pay_pal_invoicing_python_sdk.pydantic.configuration import Configuration as ConfigurationPydantic
from pay_pal_invoicing_python_sdk.pydantic.money import Money as MoneyPydantic
from pay_pal_invoicing_python_sdk.pydantic.invoices_create_draft_invoice422_response import InvoicesCreateDraftInvoice422Response as InvoicesCreateDraftInvoice422ResponsePydantic
from pay_pal_invoicing_python_sdk.pydantic.error_default import ErrorDefault as ErrorDefaultPydantic
from pay_pal_invoicing_python_sdk.pydantic.invoice import Invoice as InvoicePydantic
from pay_pal_invoicing_python_sdk.pydantic.refunds import Refunds as RefundsPydantic
from pay_pal_invoicing_python_sdk.pydantic.invoice_status import InvoiceStatus as InvoiceStatusPydantic
from pay_pal_invoicing_python_sdk.pydantic.invoicer_info import InvoicerInfo as InvoicerInfoPydantic
from pay_pal_invoicing_python_sdk.pydantic.recipient_info import RecipientInfo as RecipientInfoPydantic
from pay_pal_invoicing_python_sdk.pydantic.payments import Payments as PaymentsPydantic
from pay_pal_invoicing_python_sdk.pydantic.item import Item as ItemPydantic
from pay_pal_invoicing_python_sdk.pydantic.invoice_detail import InvoiceDetail as InvoiceDetailPydantic
from pay_pal_invoicing_python_sdk.pydantic.amount_summary_detail import AmountSummaryDetail as AmountSummaryDetailPydantic

# body param
SchemaForRequestBodyApplicationJson = InvoiceSchema


request_body_invoice = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor201ResponseBodyApplicationJson = InvoiceSchema
SchemaFor201ResponseBodyMultipartMixed = InvoiceSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: Invoice


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: Invoice


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor201ResponseBodyMultipartMixed),
    },
)
SchemaFor400ResponseBodyApplicationJson = InvoicesCreateDraftInvoiceResponseSchema
SchemaFor400ResponseBodyMultipartMixed = InvoicesCreateDraftInvoice400ResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: InvoicesCreateDraftInvoiceResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: InvoicesCreateDraftInvoiceResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor400ResponseBodyMultipartMixed),
    },
)
SchemaFor403ResponseBodyApplicationJson = Error403Schema
SchemaFor403ResponseBodyMultipartMixed = Error403Schema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: Error403


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: Error403


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor403ResponseBodyMultipartMixed),
    },
)
SchemaFor422ResponseBodyApplicationJson = InvoicesCreateDraftInvoice422ResponseSchema
SchemaFor422ResponseBodyMultipartMixed = InvoicesCreateDraftInvoice422ResponseSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: InvoicesCreateDraftInvoice422Response


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: InvoicesCreateDraftInvoice422Response


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
        'multipart/mixed': api_client.MediaType(
            schema=SchemaFor422ResponseBodyMultipartMixed),
    },
)
SchemaFor0ResponseBodyApplicationJson = ErrorDefaultSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: ErrorDefault


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: ErrorDefault


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
    'multipart/mixed',
)


class BaseApi(api_client.Api):

    def _create_draft_invoice_mapped_args(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if id is not None:
            _body["id"] = id
        if parent_id is not None:
            _body["parent_id"] = parent_id
        if items is not None:
            _body["items"] = items
        if detail is not None:
            _body["detail"] = detail
        if invoicer is not None:
            _body["invoicer"] = invoicer
        if primary_recipients is not None:
            _body["primary_recipients"] = primary_recipients
        if additional_recipients is not None:
            _body["additional_recipients"] = additional_recipients
        if items is not None:
            _body["items"] = items
        if configuration is not None:
            _body["configuration"] = configuration
        if amount is not None:
            _body["amount"] = amount
        if due_amount is not None:
            _body["due_amount"] = due_amount
        if gratuity is not None:
            _body["gratuity"] = gratuity
        if payments is not None:
            _body["payments"] = payments
        if refunds is not None:
            _body["refunds"] = refunds
        if links is not None:
            _body["links"] = links
        args.body = _body
        return args

    async def _acreate_draft_invoice_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create draft invoice
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/invoicing/invoices',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_invoice.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_draft_invoice_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create draft invoice
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/invoicing/invoices',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_invoice.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateDraftInvoiceRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_draft_invoice(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_draft_invoice_mapped_args(
            detail=detail,
            id=id,
            parent_id=parent_id,
            items=items,
            invoicer=invoicer,
            primary_recipients=primary_recipients,
            additional_recipients=additional_recipients,
            items=items,
            configuration=configuration,
            amount=amount,
            due_amount=due_amount,
            gratuity=gratuity,
            payments=payments,
            refunds=refunds,
            links=links,
        )
        return await self._acreate_draft_invoice_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_draft_invoice(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_draft_invoice_mapped_args(
            detail=detail,
            id=id,
            parent_id=parent_id,
            items=items,
            invoicer=invoicer,
            primary_recipients=primary_recipients,
            additional_recipients=additional_recipients,
            items=items,
            configuration=configuration,
            amount=amount,
            due_amount=due_amount,
            gratuity=gratuity,
            payments=payments,
            refunds=refunds,
            links=links,
        )
        return self._create_draft_invoice_oapg(
            body=args.body,
        )

class CreateDraftInvoice(BaseApi):

    async def acreate_draft_invoice(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
        validate: bool = False,
        **kwargs,
    ) -> InvoicePydantic:
        raw_response = await self.raw.acreate_draft_invoice(
            detail=detail,
            id=id,
            parent_id=parent_id,
            items=items,
            invoicer=invoicer,
            primary_recipients=primary_recipients,
            additional_recipients=additional_recipients,
            items=items,
            configuration=configuration,
            amount=amount,
            due_amount=due_amount,
            gratuity=gratuity,
            payments=payments,
            refunds=refunds,
            links=links,
            **kwargs,
        )
        if validate:
            return InvoicePydantic(**raw_response.body)
        return api_client.construct_model_instance(InvoicePydantic, raw_response.body)
    
    
    def create_draft_invoice(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
        validate: bool = False,
    ) -> InvoicePydantic:
        raw_response = self.raw.create_draft_invoice(
            detail=detail,
            id=id,
            parent_id=parent_id,
            items=items,
            invoicer=invoicer,
            primary_recipients=primary_recipients,
            additional_recipients=additional_recipients,
            items=items,
            configuration=configuration,
            amount=amount,
            due_amount=due_amount,
            gratuity=gratuity,
            payments=payments,
            refunds=refunds,
            links=links,
        )
        if validate:
            return InvoicePydantic(**raw_response.body)
        return api_client.construct_model_instance(InvoicePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_draft_invoice_mapped_args(
            detail=detail,
            id=id,
            parent_id=parent_id,
            items=items,
            invoicer=invoicer,
            primary_recipients=primary_recipients,
            additional_recipients=additional_recipients,
            items=items,
            configuration=configuration,
            amount=amount,
            due_amount=due_amount,
            gratuity=gratuity,
            payments=payments,
            refunds=refunds,
            links=links,
        )
        return await self._acreate_draft_invoice_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        detail: InvoiceDetail,
        id: typing.Optional[str] = None,
        parent_id: typing.Optional[str] = None,
        items: typing.Optional[InvoiceStatus] = None,
        invoicer: typing.Optional[InvoicerInfo] = None,
        primary_recipients: typing.Optional[typing.List[RecipientInfo]] = None,
        additional_recipients: typing.Optional[typing.List[EmailAddress]] = None,
        items: typing.Optional[typing.List[Item]] = None,
        configuration: typing.Optional[Configuration] = None,
        amount: typing.Optional[AmountSummaryDetail] = None,
        due_amount: typing.Optional[Money] = None,
        gratuity: typing.Optional[Money] = None,
        payments: typing.Optional[Payments] = None,
        refunds: typing.Optional[Refunds] = None,
        links: typing.Optional[typing.List[LinkDescription]] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_draft_invoice_mapped_args(
            detail=detail,
            id=id,
            parent_id=parent_id,
            items=items,
            invoicer=invoicer,
            primary_recipients=primary_recipients,
            additional_recipients=additional_recipients,
            items=items,
            configuration=configuration,
            amount=amount,
            due_amount=due_amount,
            gratuity=gratuity,
            payments=payments,
            refunds=refunds,
            links=links,
        )
        return self._create_draft_invoice_oapg(
            body=args.body,
        )

