# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_cancel.post import CancelSentInvoiceRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices.post import CreateDraftInvoiceRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id.delete import DeleteDraftOrScheduledInvoiceRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_payments_transaction_id.delete import DeleteExternalPaymentRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_refunds_transaction_id.delete import DeleteExternalRefundRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_generate_next_invoice_number.post import GenerateNextInvoiceNumberRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_generate_qr_code.post import GenerateQrCodeRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id.get import GetDetailsRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices.get import GetInvoicesRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_payments.post import RecordPaymentRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_refunds.post import RecordRefundRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_send.post import SendInvoiceRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_remind.post import SendReminderRaw
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id.put import UpdateFullInvoiceRaw


class InvoicesApiRaw(
    CancelSentInvoiceRaw,
    CreateDraftInvoiceRaw,
    DeleteDraftOrScheduledInvoiceRaw,
    DeleteExternalPaymentRaw,
    DeleteExternalRefundRaw,
    GenerateNextInvoiceNumberRaw,
    GenerateQrCodeRaw,
    GetDetailsRaw,
    GetInvoicesRaw,
    RecordPaymentRaw,
    RecordRefundRaw,
    SendInvoiceRaw,
    SendReminderRaw,
    UpdateFullInvoiceRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
