# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_cancel.post import CancelSentInvoice
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices.post import CreateDraftInvoice
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id.delete import DeleteDraftOrScheduledInvoice
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_payments_transaction_id.delete import DeleteExternalPayment
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_refunds_transaction_id.delete import DeleteExternalRefund
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_generate_next_invoice_number.post import GenerateNextInvoiceNumber
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_generate_qr_code.post import GenerateQrCode
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id.get import GetDetails
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices.get import GetInvoices
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_payments.post import RecordPayment
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_refunds.post import RecordRefund
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_send.post import SendInvoice
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id_remind.post import SendReminder
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_invoices_invoice_id.put import UpdateFullInvoice
from pay_pal_invoicing_python_sdk.apis.tags.invoices_api_raw import InvoicesApiRaw


class InvoicesApi(
    CancelSentInvoice,
    CreateDraftInvoice,
    DeleteDraftOrScheduledInvoice,
    DeleteExternalPayment,
    DeleteExternalRefund,
    GenerateNextInvoiceNumber,
    GenerateQrCode,
    GetDetails,
    GetInvoices,
    RecordPayment,
    RecordRefund,
    SendInvoice,
    SendReminder,
    UpdateFullInvoice,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InvoicesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InvoicesApiRaw(api_client)
