# coding: utf-8

"""
    Invoices

    Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.

    The version of the OpenAPI document: 2.3
    Generated by: https://konfigthis.com
"""

from pay_pal_invoicing_python_sdk.paths.v2_invoicing_templates.post import CreateTemplate
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_templates_template_id.delete import DeleteById
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_templates.get import ListDetails
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_templates_template_id.get import ShowDetailsById
from pay_pal_invoicing_python_sdk.paths.v2_invoicing_templates_template_id.put import UpdateFullTemplate
from pay_pal_invoicing_python_sdk.apis.tags.templates_api_raw import TemplatesApiRaw


class TemplatesApi(
    CreateTemplate,
    DeleteById,
    ListDetails,
    ShowDetailsById,
    UpdateFullTemplate,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TemplatesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TemplatesApiRaw(api_client)
